steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy unplan-server-dev \
          --source . \
          --region asia-northeast3 \
          --allow-unauthenticated \
          --set-env-vars "SPRING_PROFILES_ACTIVE=dev" \
          --set-env-vars "DEVELOP_DB_URL=jdbc:postgresql:///unplan_dev?cloudSqlInstance=project-444d4167-0f20-42df-85d:asia-northeast3:unplan-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory" \
          --set-env-vars "DEVELOP_DB_USERNAME=$$DB_USERNAME" \
          --set-env-vars "DEVELOP_DB_PASSWORD=$$DB_PASSWORD" \
          --set-env-vars "JWT_SECRET=$$JWT_SECRET" \
          --set-env-vars "JWT_ACCESS_EXPIRATION=3600000" \
          --set-env-vars "JWT_REFRESH_EXPIRATION=2592000000" \
          --set-env-vars "GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID" \
          --set-env-vars "DEVELOP_SERVER_URL=https://dev-api.un-plan.com"
    secretEnv: ['DB_USERNAME', 'DB_PASSWORD', 'JWT_SECRET', 'GOOGLE_CLIENT_ID']

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/project-444d4167-0f20-42df-85d/secrets/dev_db_username/versions/latest
      env: 'DB_USERNAME'
    - versionName: projects/project-444d4167-0f20-42df-85d/secrets/dev_db_password/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/project-444d4167-0f20-42df-85d/secrets/dev_jwt_secret/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/project-444d4167-0f20-42df-85d/secrets/dev_google_client_id/versions/latest
      env: 'GOOGLE_CLIENT_ID'