spring:
  application:
    name: unplan-server
  profiles:
    default: local
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
  config:
    import: optional:file:.env[.properties]

gemini:
  api-key: ${GEMINI_API_KEY:}

server:
  port: ${PORT:8080}
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

swagger:
  server-url: ${SWAGGER_SERVER_URL:http://localhost:8080}
  description: ${SWAGGER_DESCRIPTION:Local Server}

google:
  client-id: ${GOOGLE_CLIENT_ID}