spring:
  datasource:
    url: ${DEVELOP_DB_URL:jdbc:postgresql://8.230.24.118:5432/unplan_dev}
    username: ${DEVELOP_DB_USERNAME}
    password: ${DEVELOP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false


jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000  #1시간
  refresh-expiration: 2592000000 #30일

swagger:
  server-url: ${DEVELOP_SERVER_URL:https://dev-api.un-plan.com}
  description: Dev Server
