spring:
  datasource:
    url: ${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/unplan}
    username: ${LOCAL_DB_USERNAME:unplan}
    password: ${LOCAL_DB_PASSWORD:unplan}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: false
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000  #1시간
  refresh-expiration: 2592000000 #30일

swagger:
  server-url: http://localhost:8080
  description: Local Server